// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCabt3AXAmUej6DbFz4LwyCBjFc_QEM9Sg',
    appId: '1:789674956313:android:08ea5db988d34977827c88',
    messagingSenderId: '789674956313',
    projectId: 'kasirsupertesting',
    storageBucket: 'kasirsupertesting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpvI0ymk-SwT7QtbVfRW-iUjMU1_sJ-0',
    appId: '1:789674956313:ios:fa55b78ef1c85756827c88',
    messagingSenderId: '789674956313',
    projectId: 'kasirsupertesting',
    storageBucket: 'kasirsupertesting.appspot.com',
    iosBundleId: 'com.kasirsupermobile.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuyrhmxtnmfBSB5Upx0pHpQfHgVI3gvBM',
    appId: '1:789674956313:web:0e3dc90a511a7891827c88',
    messagingSenderId: '789674956313',
    projectId: 'kasirsupertesting',
    authDomain: 'kasirsupertesting.firebaseapp.com',
    storageBucket: 'kasirsupertesting.appspot.com',
    measurementId: 'G-E6YH9354E0',
  );

}